[package]
name = "exa-sdk"
version = "0.1.0"
edition = "2021"
description = "Rust SDK for the Exa API"
license = "MIT"
repository = "https://github.com/fdionisi/exa-sdk"
readme = "README.md"
keywords = ["exa", "api", "sdk", "search"]
categories = ["api-bindings"]

[dependencies]
anyhow = "1.0.86"
futures = "*"
http-client = { git = "https://github.com/fdionisi/http-client", rev = "033ac96ab12ac3d13b78f9725b237380917c7094" }
secrecy = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.63"
url = "2.5.2"

[dev-dependencies]
http-client-reqwest = { git = "https://github.com/fdionisi/http-client", rev = "033ac96ab12ac3d13b78f9725b237380917c7094" }
mockito = "1.4.0"
tokio = { version = "1.0", features = ["full"] }
